addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.10")
addSbtPlugin("com.jamesward" % "play-auto-refresh" % "0.0.16")
addSbtPlugin("org.irundaia.sbt" % "sbt-sassify" % "1.4.11")
addSbtPlugin("com.lightbend.sbt" % "sbt-javaagent" % "0.1.4")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.3")
